android.useAndroidX=true
android.enableJetifier=false

# Redirigir temporales de SQLite para evitar AccessDeniedException en Windows
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8 -Dorg.sqlite.tmpdir=build/tmp/sqlite
org.gradle.daemon.performance.disable-logging=true
org.gradle.configuration-cache=true

