android.useAndroidX=true
android.enableJetifier=false

# Redirigir temporales de SQLite para evitar AccessDeniedException en Windows
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8 -Dorg.sqlite.tmpdir=build/tmp/sqlite
org.gradle.daemon.performance.disable-logging=true
org.gradle.configuration-cache=true

VOYAGER_BACKEND_BASE_URL="https://ktvcj1a32d.execute-api.us-east-1.amazonaws.com/prod/backend"
VOYAGER_AI_BASE_URL="https://ktvcj1a32d.execute-api.us-east-1.amazonaws.com/prod/ai"
VOYAGER_CHAT_BROKER_URL="wss://smarttrip-alb-147770928.us-east-1.elb.amazonaws.com:8080/api/v1/ws-chat"

